# Generated by Django 4.0 on 2023-12-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
