# Generated by Django 4.0 on 2023-10-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
