# Generated by Django 4.0 on 2023-10-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='first_name',
        ),
    ]
